### ISSUE TITLE
Tom Jones

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/resume_connection#22]
While Tom would hope to follow this and later contribute, he doesn't think he needs to continue to be named as a document author. I suggest we add an appropriate Acknowledgment note that he was an author of the original document.

**Comment by NicoKos** [comment]
Fixed with : 
- https://github.com/NicoKos/resume_connection/pull/20/commits/ce4cf473a440d8fa5d5b19f70a54e192096550f1
- https://github.com/NicoKos/resume_connection/pull/21/commits/4db439d8c93f9de388c037eb9b84203df6110378

Thanks a lot Tom for your help !

**Comment by gorryfair** [comment]
Will be resolved in next rev

**Comment by gorryfair** [comment]
closed issue
