### ISSUE TITLE
BDF Frame: Server trust?

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/resume_connection#24]
I have trouble with this text:

The server SHOULD NOT trust the content of the BDP Frame received from the client.

So, this may be me, but I don't really understand the main issues here. What I understand is (I think):

1. if this is a 0RTT frame, then the security has not been agreed. That has security implications.
2.I think  the server send both an encrypted  blob (aka opaque token) to the client and some descriptive info about what the blob contains. Clearly the client is unable to tell if the blob actually matches the description, but a receiver anyway trusts a sender for CC guidance. The description is likely enough to allow a client to choose to accelerate window growth or not (I doubt there is a lot more to be optimised based on specific params) - so I motivate anyway that the client chooses to accept and use, or reject the proposed acceleration (e.g. rejecting when the flow is know to be relatively short - avoiding the "pain" of potential overshot; when a client knows the capacity is reduced (such as a path change, or when the client has connectivity to a different server); or when the client wishes to use the "acceleration:" with a different connection;

The current text seems to ignore that the server can add an opaque blob that it CAN trust - did we decide on this?

**Comment by gorryfair** [comment]
This issue also applies a little to careful resume, which mostly follows the approach above, but not in all places.

I found the statement below interesting ... if we have a sender-supplied opaque blob, then the receiver can not modify this - but can read the description. e.g. this relates to this text:
"This allows a receiver
            to read, but not modify, the saved_rtt and saved_bb parameters and
            could enable a client to decide whether the new
            parameters are thought appropriate, based on client-side information about
            the network conditions, connectivity, or needs of the new
            connection."
- To be clear, I am content with read decsription and can not modify, but can reject the "upgrade".

**Comment by gorryfair** [comment]
This still needs thought, but a tool to fix it could be #27

**Comment by NicoKos** [comment]
I have been thinking over it further and I am now wondering whether we need to do anything particular appart from saying that NEW_TOKEN are encrypted and protected as any other QUIC Frame. 
For the BDP Frame, Emile regularly mentioned that it is as protected as the early_data extension used for validating 0-RTT data. 
What do you think?

**Comment by NicoKos** [comment]
This issue can be closed as it is covered by Issue #27
