### ISSUE TITLE
BDF Frame: Do we need to based BDP Frame on ORTT?

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/resume_connection#25]
It seems that 0RTT is not so widely available, and might have quite some API complexity.

Do we need to based BDP Frame on ORTT?
- Maybe not.
- This might rather depend on whether you think there are important benefits in saving the initial RTT of data.
- I'm still arguing against doing any dramatic change of IW before any data has been exchanged. To me, but just makes too many possibilities of flows jumping into severely congested bottlenecks. If you have the reassurance of IW data being ACK'ed and the RTT being "consistent" then you maybe have the right to be braver, in ORRT I am much less sure.
- Could we think to build the mechanism around the 1RTT part of the connection? ... doing so might also gain more support from the QUIC WG, who currently see all 0RTT stuff as fun, but in the distance.

**Comment by gorryfair** [comment]
0RTT is also mentioned in careful resume. If we decode not to pursue 0RTT, then I think we need to revise both documents

**Comment by NicoKos** [comment]
I think that with PR https://github.com/NicoKos/resume_connection/pull/31 we clarify that not only 0RTT sessions are concerned.

**Comment by NicoKos** [comment]
I propose to close this issue with PR #31
