### ISSUE TITLE
Should we add an expiration date to the BDPFRAME (or something similar?)

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#29]

**Comment by gorryfair** [comment]
I think so - although I've tagged also for careful resume, because the same notion of expiring state needs might apply to local caches.

**Comment by gorryfair** [comment]
Note we just rely on the sender to enforce a local policy of when to allow, but putting this is the BDP frame allows the sender to be stateless?

**Comment by NicoKos** [comment]
There is already a lifetime (extension_lifetime) parameter in the BDP Frame Extension.

**Comment by NicoKos** [comment]
I have provided more info in PR #32 
This issue will be linked to this PR. 
FYI , token SHOULD be associated with a timer (RFC 9000).
