### ISSUE TITLE
How do we identify the path ?  

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#36]
This identification could be different depending on the implementation solution.

**Comment by NicoKos** [comment]
Path Token as suggest by John

**Comment by NicoKos** [comment]
Path Token : unique number generated by the sender - can contain many things (IP, interface, randomness - NAT) can be seen by both client and senders.

**Comment by NicoKos** [comment]
It is then up to the sender to validate the path token upon reception of the bdpframe.

**Comment by gorryfair** [comment]
When we explain this we can talk about:
- RFC 9040 Section 8,  control sharing
- Privacy extensions in IPv6 - i.e. where the token does not include the actual IP, but the base info used to make the address
- Privacy considerations RFC
- Maybe something from PANRG
The above can be pit in a separate text file until we are ready to add

**Comment by gorryfair** [comment]
Yes sender validates this. See the document proposed by GF.
