### ISSUE TITLE
Improve document organization

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#58]
From John Border 
In Section 3, when I got to the Retreat Phase description, I paused because it seemed like more is needed.  I later found that more in Section 4.5.  I think it would be helpful, for all of the phases, to put pointers to the sections which have more discussion about them.  (Or maybe a blanket pointer to Section 4 for more details at the front of Section 3.)

**Comment by gorryfair** [comment]
This partly needs to be addressed when we decide on the various safety techniques. I added cross references to the techniques in PR #70
