### ISSUE TITLE
Extension activation

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#63]
From John Border: 
It is not entirely clear what the difference is between using BDP_FRAME and activating the optimization.  Is the idea to allow saving the CC values at the sender without sending them in a BDP_FRAME to the receiver and the use of saved CC values is the optimization?

**Comment by gorryfair** [comment]
So: On the one hand, Careful Resume is a sender method, that defines a safe way to change the congestion controller; 
On the other hand, BDP Frame relies on Careful Resume to take action, but then allows a receiver to tell the sender when it wishes to use the optimisation (and by implication if a receiver doesn't ask - then not to use the optimisation) - a receiver could send an explicit request not to use the optimisation. It also allows a sender to avoid keeping longer-term state, if that helps the sender.

**Comment by NicoKos** [comment]
Issue linked with a proposed PR #73
