### ISSUE TITLE
Client identification clarification

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/resume_connection#64]
From John Border 

Section 3.2 re the first sentence in the third paragraph that the mechanism for identifying that it is the same receiver is being left independent from the specification of BDP-FRAME.  Or is this referring to the Endpoint Token discussed in Section 3.3.1 in which case maybe that section should be pointed to?

**Comment by gorryfair** [comment]
I think we need text to point to endpoint token.

**Comment by NicoKos** [comment]
Text proposed in PR#72 !
